#!/bin/bash

bat0=/sys/class/power_supply/BAT0/
bat1=/sys/class/power_supply/BAT1/

per0="$(cat "$bat0/capacity")"
per1="$(cat "$bat1/capacity")"

per=$(($(($per0+$per1))/2))

echo "Battery: $per" && exit
