#!/bin/bash

bat0=/sys/class/power_supply/BAT0/
bat1=/sys/class/power_supply/BAT1/
ac=/sys/class/power_supply/AC/

status="$(cat "$ac/online")"
per0="$(cat "$bat0/capacity")"
per1="$(cat "$bat1/capacity")"

per=$(($(($per0+$per1))/2))
status_show=""

if [[ $status -eq 1 ]]; then
    status_show="⇑"
elif [[ $status -eq 0 ]]; then
    status_show="⇓"
else
    status_show"❔"
fi

if [[ $per -lt 11 && $status -eq 0 ]]; then
    brightnessctl -q s 152
fi

echo "$per$status_show" && exit
